export const GHS_AUDIT_ACTIONS = {
  CREATE_PRODUCT: 'CREATE_PRODUCT',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  DELETE_PRODUCT: 'DELETE_PRODUCT',
  UPLOAD_IMAGE: 'UPLOAD_IMAGE',
  REMOVE_IMAGE: 'REMOVE_IMAGE',
  UPLOAD_MODEL: 'UPLOAD_MODEL',
  UPLOAD_VIDEO: 'UPLOAD_VIDEO',
  CREATE_QUOTE: 'CREATE_QUOTE',
  UPDATE_QUOTE: 'UPDATE_QUOTE',
  GENERATE_PDF: 'GENERATE_PDF',
  SEND_QUOTE: 'SEND_QUOTE',
  UPDATE_SHOWROOM_V2_CONTENT: 'UPDATE_SHOWROOM_V2_CONTENT',
} as const;

export type GhsAuditAction = (typeof GHS_AUDIT_ACTIONS)[keyof typeof GHS_AUDIT_ACTIONS];

export const GHS_AUDIT_ACTION_VALUES = Object.values(GHS_AUDIT_ACTIONS) as GhsAuditAction[];

export const GHS_AUDIT_ENTITIES = {
  PRODUCT: 'Product',
  QUOTE: 'Quote',
  SHOWROOM_V2_CONTENT: 'ShowroomV2Content',
} as const;

export type GhsAuditEntity = (typeof GHS_AUDIT_ENTITIES)[keyof typeof GHS_AUDIT_ENTITIES];

export const GHS_AUDIT_ENTITY_VALUES = Object.values(GHS_AUDIT_ENTITIES) as GhsAuditEntity[];
