import type { ShowroomV2ContentContract } from './site';

export const SHOWROOM_V2_DEFAULT_CONTENT: ShowroomV2ContentContract = {
  brand: {
    name: 'GỐM HOA SEN',
    tagline: 'Gốm sứ nghệ thuật cho không gian sống hiện đại',
    subtitle: 'Tinh hoa men Việt — Chế tác thủ công — Kể chuyện qua từng đường nét',
    location: 'Số 41 Giang Cao, Bát Tràng, Hà Nội',
    phone: '0961 189 292',
    email: 'Đang cập nhật',
    facebookHref: '',
  },
  navigation: {
    items: [
      { label: 'Trang chủ', href: '/' },
      { label: 'Giới thiệu', href: '/gioi-thieu' },
      { label: 'Sản phẩm', href: '/san-pham' },
      { label: 'Bộ sưu tập', href: '/bo-suu-tap' },
      { label: 'Tin tức', href: '/tin-tuc' },
      { label: 'Liên hệ', href: '/lien-he' },
    ],
  },
  notFound: {
    eyebrow: '404',
    title: 'Không tìm thấy trang',
    body: 'Nội dung bạn tìm kiếm không tồn tại hoặc đã được chuyển sang địa chỉ khác.',
    backLabel: 'Về trang chủ',
  },
  home: {
    heroTitle: 'GỐM HOA SEN',
    heroSubtitle: 'Gìn giữ tinh hoa gốm Việt',
    heroBody:
      'Nét đẹp truyền thống hòa quyện cùng nghệ thuật đương đại,\n' +
      'tạo nên những kiệt tác gốm sứ độc bản vượt thời gian.',
    heroCtaLabel: 'Khám phá',
    heroCtaHref: '/san-pham',
    heroBg: '',
    heroModelUrl: '/assets/product/brass_vase_textured.glb',
    heroModelPoster: '/assets/product/hero-transparent.png',
    heroReferenceImage: '/assets/product/hero-reference-cutout.png',
    introSkipLabel: 'Bỏ qua',
    logoSubtext: 'TINH HOA GỐM VIỆT',
    languageLabel: 'VI',
    scrollHintLabel: 'SCROLL',
    heroModelAlt: 'Bình Hoa Sen Vàng — gốm thủ công Việt Nam, xoay 360 độ',
    interactionHint: 'Kéo chuột\nđể xoay',
    interactionFeatures: [
      'Men hóa thạch',
      'Vẽ tay thủ công',
      'Dáng phỏng cổ',
      'Nung nhiệt cao',
    ],
    heritageEyebrow: 'Tinh hoa di sản',
    heritageTitle: 'Giữ hồn Việt\ntrong từng sản phẩm gốm',
    heritageBody:
      'Mỗi sản phẩm là kết tinh của đất, lửa và bàn tay nghệ nhân — ' +
      'hành trình từ đất sét đến tác phẩm bất tử.',
    heritageCtaLabel: 'Tìm hiểu thêm',
    heritageCtaHref: '/gioi-thieu#ngu-hanh',
    collectionEyebrow: 'Bộ sưu tập nổi bật',
    collectionTitle: 'Kiệt tác gốm Việt\ncho không gian thiêng và đẹp',
    collectionCtaLabel: 'Xem tất cả',
    collectionCtaHref: '/bo-suu-tap',
    footerCopyright: '© {year} GỐM HOA SEN. Bản quyền được bảo lưu.',
    collections: [
      {
        img: '/assets/reference/collection-binh-gom-ref.png',
        title: 'Bình Gốm',
        sub: 'Tinh xảo và trang nhã',
        href: '/danh-muc?type=binh-hoa',
      },
      {
        img: '/assets/reference/collection-binh-hut-loc-ref.png',
        title: 'Bình Hút Lộc',
        sub: 'Phú quý và thịnh vượng',
        href: '/danh-muc?collection=phu-quy',
      },
      {
        img: '/assets/reference/collection-bo-do-tho-ref.png',
        title: 'Bộ Đồ Thờ',
        sub: 'Tôn kính và thiêng liêng',
        href: '/danh-muc?collection=hoa-sen',
      },
      {
        img: '/assets/reference/collection-trang-tri-ref.png',
        title: 'Trang Trí',
        sub: 'Nghệ thuật và đẳng cấp',
        href: '/danh-muc?type=decor',
      },
    ],
    process: [
      {
        img: '/assets/reference/process-men-hoa-thach.png',
        title: 'Men hóa thạch',
        desc: 'Lớp men cổ truyền độc bản',
        position: '50% 50%',
      },
      {
        img: '/assets/reference/process-ve-tay-thu-cong.png',
        title: 'Vẽ tay thủ công',
        desc: 'Từng nét vẽ mang hồn Việt',
        position: '50% 50%',
      },
      {
        img: '/assets/reference/process-nung-nhiet-cao.png',
        title: 'Nung nhiệt cao',
        desc: 'Bền đẹp cùng thời gian',
        position: '100% 50%',
      },
    ],
    promises: [
      {
        title: 'Thủ công thuần Việt',
        desc: 'Từng sản phẩm đều được làm tay bởi nghệ nhân làng nghề',
      },
      {
        title: 'Men cổ truyền',
        desc: 'Bí quyết men gia truyền qua nhiều thế hệ',
      },
      {
        title: 'Di sản văn hóa',
        desc: 'Lưu giữ tinh hoa gốm sứ Việt Nam ngàn năm',
      },
      {
        title: 'Bảo hành trọn đời',
        desc: 'Cam kết chất lượng và tính nguyên bản của từng hiện vật',
      },
    ],
  },
  about: {
    heroEyebrow: 'Về Gốm Hoa Sen',
    heroTitle: 'Hành trình giữ lửa',
    heroDesc:
      'Từ những ngày đầu tiên, Gốm Hoa Sen đã mang trong mình sứ mệnh gìn giữ ' +
      'và phát triển tinh hoa nghệ thuật gốm sứ truyền thống Việt Nam.',
    heroBg: '/assets/about/about-hero.jpg',
    quoteText:
      'Gốm không chỉ là đất và lửa, mà còn là tâm hồn của người thợ, ' +
      'là hồn cốt của dân tộc.',
    quoteAuthor: 'Nghệ nhân Gốm Hoa Sen',
    quoteBg: '/assets/about/about-hon.jpg',
    heroCtaLabel: 'Khám phá hành trình gốm Việt',
    heroCtaHref: '#ngu-hanh',
    heroImageAlt: 'Tượng Phật gốm sứ',
    elements: [
      {
        id: 'dat',
        title: 'ĐẤT',
        desc: 'Chọn lọc tinh hoa từ lòng đất, dẻo dai và thuần khiết.',
        img: '/assets/about/about-dat.jpg',
        iconType: 'mountain',
        isActive: false,
      },
      {
        id: 'tam',
        title: 'TÂM',
        desc: 'Từng nét vẽ, từng chi tiết đều gửi gắm tâm huyết người thợ.',
        img: '/assets/about/about-tam.jpg',
        iconType: 'lotus',
        isActive: true,
      },
      {
        id: 'men',
        title: 'MEN',
        desc: 'Men cổ truyền độc bản, màu sắc sâu lắng theo thời gian.',
        img: '/assets/about/about-men.jpg',
        iconType: 'droplet',
        isActive: false,
      },
      {
        id: 'lua',
        title: 'LỬA',
        desc: 'Nung ở nhiệt độ cao, thử thách để tạo nên giá trị bền vững.',
        img: '/assets/about/about-lua.jpg',
        iconType: 'flame',
        isActive: false,
      },
      {
        id: 'hon',
        title: 'HỒN',
        desc: 'Thổi hồn vào gốm Việt, gìn giữ văn hóa, nối dài truyền thống.',
        img: '/assets/about/about-hon.jpg',
        iconType: 'aperture',
        isActive: false,
      },
    ],
  },
  collections: {
    heroEyebrow: '03 — Bộ Sưu Tập',
    heroTitle: 'Tinh hoa gốm Việt\nqua từng thời đại',
    heroDesc:
      'Mỗi tác phẩm là sự kết tinh của đất, men, lửa và tâm người thợ. ' +
      'Gìn giữ giá trị truyền thống, tôn vinh vẻ đẹp Việt trong ngôn ngữ nghệ thuật đương đại.',
    heroBg: '/assets/collections/collection-hero.jpg',
    heroCtaLabel: 'Khám phá bộ sưu tập',
    heroCtaHref: '#collections-grid',
    tileCtaLabel: 'Khám phá',
    rows: {
      row1: [
        {
          id: 'c1',
          title: 'Đồ Thờ Gốm Sứ Cao Cấp',
          desc: 'Không gian thờ cúng trang nghiêm với những giá trị truyền thống được lưu truyền qua từng đời.',
          img: '/assets/collections/collection-altar-set.jpg',
          href: '/danh-muc?collection=hoa-sen',
          span: 6,
        },
        {
          id: 'c2',
          title: 'Lư Hương Phóng Cổ',
          desc: 'Dáng cổ xưa, hồn Việt, mang ý nghĩa tâm linh sâu sắc và trường tồn.',
          img: '/assets/collections/collection-incense-burner.jpg',
          href: '/danh-muc?collection=hoa-sen',
          span: 4,
        },
      ],
      row2: [
        {
          id: 'c3',
          title: 'Bộ Đỉnh Men Hoá Thạch',
          desc: 'Men hoá thạch độc bản, màu sắc trầm mặc, càng ngắm càng mê.',
          img: '/assets/collections/collection-fossil-set.jpg',
          href: '/danh-muc?collection=hoa-sen',
          span: 1,
        },
        {
          id: 'c4',
          title: 'Bình Vôi Bình Phong Thủy',
          desc: 'Dáng bình thanh thoát, hài hòa phong thủy, hút tài lộc, vượng khí.',
          img: '/assets/collections/collection-vases.jpg',
          href: '/danh-muc?collection=phu-quy',
          span: 1,
        },
        {
          id: 'c5',
          title: 'Bộ Ngai Thờ',
          desc: 'Nét chạm khắc tinh xảo, tôn nghiêm, thể hiện đẳng cấp không gian thờ Việt.',
          img: '/assets/collections/collection-throne.jpg',
          href: '/danh-muc?collection=hoa-sen',
          span: 1,
        },
      ],
      row3: [
        {
          id: 'c6',
          title: 'Chân Đèn Bát Hương Thống Gốm',
          desc: 'Những vật phẩm không thể thiếu trong không gian thờ cúng truyền thống của người Việt.',
          img: '/assets/collections/collection-lamps.jpg',
          href: '/danh-muc?collection=hoa-sen',
          span: 6,
        },
        {
          id: 'c7',
          title: 'Từ Bàn Tay Người Thợ',
          desc: 'Mỗi nét vẽ, mỗi đường chạm là tâm huyết và niềm tự hào của người thợ gốm Việt.',
          img: '/assets/collections/collection-artisan.jpg',
          href: '/nghe-nhan',
          span: 4,
        },
      ],
    },
  },
  productsLanding: {
    heroTitle: 'CHÂN ĐÈN THỜ',
    heroSubtitle: 'Tôn nghiêm Trang trọng',
    heroDesc:
      'Chân đèn thờ được chế tác thủ công từ gốm Bát Tràng cao cấp, men nâu cổ truyền, ' +
      'đường nét tinh xảo, hoa văn Tứ Linh - sen hóa mang ý nghĩa phong thủy tốt lành, ' +
      'tôn vinh không gian thờ tự.',
    badgeText: 'Tôn vinh không gian thờ tự\nlinh thiêng và trang trọng',
    heroBg: '/assets/products/product-main-scene.jpg',
    featuredSectionLabel: 'DÒNG SẢN PHẨM NỔI BẬT',
    categories: [
      {
        id: 'tuong-phat',
        title: 'Tượng Phật',
        desc: 'Tôn nghiêm cho không gian thiền tự',
        img: '/assets/products/product-cat-1.jpg',
        href: '/danh-muc',
      },
      {
        id: 'bat-trang-cao-cap',
        title: 'Bát Tràng Cao Cấp',
        desc: 'Bộ sưu tập thủ công tuyển chọn',
        img: '/assets/products/product-cat-2.jpg',
        href: '/danh-muc',
      },
      {
        id: 'do-tho-gom',
        title: 'Đồ Thờ Gốm',
        desc: 'Hiện vật thờ cúng tinh xảo',
        img: '/assets/products/product-cat-3.jpg',
        href: '/danh-muc?collection=hoa-sen',
      },
      {
        id: 'trang-tri',
        title: 'Trang Trí',
        desc: 'Điểm nhấn nghệ thuật cho không gian sống',
        img: '/assets/products/product-cat-4.jpg',
        href: '/danh-muc?type=decor',
      },
      {
        id: 'qua-tang',
        title: 'Quà Tặng',
        desc: 'Lựa chọn trang trọng và ý nghĩa',
        img: '/assets/products/product-cat-5.jpg',
        href: '/danh-muc?collection=phu-quy',
      },
    ],
    productFeatures: [
      {
        iconType: 'lotus',
        title: 'Gốm Bát Tràng Cao Cấp',
        desc: '100% gốm sứ truyền thống',
      },
      {
        iconType: 'wind',
        title: 'Chế Tác Thủ Công Tinh Xảo',
        desc: 'Bởi nghệ nhân làng nghề',
      },
      {
        iconType: 'droplet',
        title: 'Men Nâu Cổ Truyền',
        desc: 'Bền màu – sang trọng',
      },
      {
        iconType: 'sun',
        title: 'Phong Thủy Tốt Lành',
        desc: 'Tứ Linh – sen hóa – vượng khí',
      },
    ],
    trustBadges: [
      {
        iconType: 'check',
        title: 'Chuẩn Gốm Việt',
        desc: '100% sản phẩm chính gốc Bát Tràng',
      },
      {
        iconType: 'package',
        title: 'Chế Tác Tinh Xảo',
        desc: 'Bởi nghệ nhân làng nghề',
      },
      {
        iconType: 'truck',
        title: 'Giao Hàng Toàn Quốc',
        desc: 'Đóng gói cẩn thận, giao hàng tận nơi',
      },
      {
        iconType: 'headset',
        title: 'Hỗ Trợ Tận Tâm',
        desc: 'Tư vấn phong thủy, chọn quà ý nghĩa',
      },
    ],
  },
  newsLanding: {
    heroEyebrow: 'Tạp chí Gốm Hoa Sen',
    heroTitle: 'Câu Chuyện & Tin Tức',
    heroDesc:
      'Khám phá những câu chuyện truyền cảm hứng về nghệ thuật gốm sứ, ' +
      'những sự kiện nổi bật và hành trình gìn giữ tinh hoa làng nghề truyền thống Việt Nam.',
    featuredId: 'hero',
    featuredLabel: 'Bài viết nổi bật',
    allCategoryLabel: 'Tất cả',
    emptyStateLabel: 'Chưa có bài viết nào trong chuyên mục này.',
    readArticleLabel: 'Đọc bài viết',
    backToNewsLabel: 'Quay lại Tin tức',
    relatedTitle: 'Bài viết liên quan',
    notFoundTitle: 'Không tìm thấy bài viết',
    notFoundBody: 'Bài viết bạn tìm kiếm không tồn tại hoặc đã được chuyển sang địa chỉ khác.',
    categories: [
      { id: 'nc-su-kien', name: 'Sự kiện', slug: 'su-kien' },
      { id: 'nc-nghe-thuat-gom', name: 'Nghệ thuật gốm', slug: 'nghe-thuat-gom' },
      { id: 'nc-lang-nghe', name: 'Làng nghề', slug: 'lang-nghe' },
    ],
    newsCards: [
      {
        id: 'hero',
        slug: 'trien-lam-di-san-gom-viet',
        category: 'Sự kiện',
        date: '15 THG 07, 2026',
        title: 'Triển lãm Di sản Gốm Việt: Nơi giao thoa giữa truyền thống và đương đại',
        excerpt:
          'Sự kiện thu hút hàng ngàn người yêu nghệ thuật trong và ngoài nước, trưng bày ' +
          'những bộ sưu tập gốm sứ tinh xảo nhất được chế tác riêng cho năm 2026.',
        image: '/assets/news/news-hero.jpg',
        author: 'Ban biên tập Gốm Hoa Sen',
        readingTime: '5 phút đọc',
        content:
          'Triển lãm Di sản Gốm Việt mở ra một không gian đối thoại giữa kỹ nghệ truyền thống và nhịp sống đương đại. Mỗi tác phẩm được đặt trong bối cảnh riêng để người xem cảm nhận rõ dáng gốm, sắc men và dấu tay của người thợ.\n\n' +
          'Bên cạnh những dòng men quen thuộc của Bát Tràng, triển lãm giới thiệu nhiều thử nghiệm mới về hình khối và cách bài trí. Tinh thần đổi mới được tiết chế để không làm mất đi cốt cách Việt trong từng sản phẩm.\n\n' +
          'Gốm Hoa Sen tham gia sự kiện với các tác phẩm tuyển chọn, kể lại hành trình từ đất, men, lửa đến một vật phẩm có đời sống lâu dài trong không gian của người Việt.',
      },
      {
        id: 'n1',
        slug: 'nghe-thuat-men-ran-co',
        category: 'Nghệ thuật gốm',
        date: '10 THG 07, 2026',
        title: 'Nghệ thuật men rạn cổ: Vẻ đẹp từ sự không hoàn hảo',
        excerpt:
          'Khám phá kỹ thuật phục dựng men rạn cổ thất truyền từ thế kỷ 16 qua bàn tay nghệ nhân Bát Tràng.',
        image: '/assets/news/news-1.jpg',
        author: 'Ban biên tập Gốm Hoa Sen',
        readingTime: '4 phút đọc',
        content:
          'Men rạn được nhận biết bởi mạng đường nứt tự nhiên hình thành trong quá trình nguội của lớp men. Không có hai bề mặt nào hoàn toàn giống nhau, vì vậy mỗi sản phẩm mang một dấu ấn riêng.\n\n' +
          'Để tạo được độ rạn đẹp, người thợ phải kiểm soát chặt chẽ thành phần men, độ dày lớp phủ và chu trình nhiệt. Chỉ một thay đổi nhỏ trong lò cũng có thể làm sắc men lệch khỏi dự tính.\n\n' +
          'Vẻ đẹp của men rạn không nằm ở sự đồng đều tuyệt đối, mà ở cách những đường rạn lưu giữ thời gian và làm nổi bật chiều sâu của họa tiết thủ công.',
      },
      {
        id: 'n2',
        slug: 'nhip-song-ben-lo-bau-co',
        category: 'Làng nghề',
        date: '05 THG 07, 2026',
        title: 'Nhịp sống bên lò bầu cổ cuối cùng của làng gốm',
        excerpt:
          'Lò bầu cổ rêu phong vẫn đỏ lửa đêm ngày, lưu giữ nhịp đập của một thời kỳ hưng thịnh.',
        image: '/assets/news/news-2.jpg',
        author: 'Ban biên tập Gốm Hoa Sen',
        readingTime: '5 phút đọc',
        content:
          'Lò bầu từng là trung tâm của mỗi xưởng gốm, nơi nhiều gia đình cùng chia sẻ một mẻ nung kéo dài. Nhịp làm việc quanh lò tạo nên nếp sinh hoạt đặc trưng của làng nghề.\n\n' +
          'Người thợ lò quan sát màu lửa, tiếng gió và độ nóng trên từng khoang để điều chỉnh nhiên liệu. Kinh nghiệm ấy được truyền qua thực hành nhiều hơn qua sách vở.\n\n' +
          'Giữ lại một lò bầu cổ không chỉ là bảo tồn kiến trúc. Đó còn là cách lưu giữ ký ức lao động và tri thức bản địa đã làm nên danh tiếng của gốm Việt.',
      },
      {
        id: 'n3',
        slug: 'tinh-hoa-dat-viet-tai-paris',
        category: 'Sự kiện',
        date: '28 THG 06, 2026',
        title: "Ra mắt bộ sưu tập 'Tinh Hoa Đất Việt' tại Paris",
        excerpt:
          'Gốm Hoa Sen tự hào mang tinh hoa thủ công Việt Nam giới thiệu tại không gian triển lãm Maison et Objet.',
        image: '/assets/news/news-3.jpg',
        author: 'Ban biên tập Gốm Hoa Sen',
        readingTime: '4 phút đọc',
        content:
          'Bộ sưu tập Tinh Hoa Đất Việt được xây dựng từ những hình ảnh quen thuộc như hoa sen, mây, sóng nước và dáng bình truyền thống. Các chi tiết được tinh giản để phù hợp với không gian sống đương đại.\n\n' +
          'Tại Paris, sản phẩm được trưng bày cùng câu chuyện về vật liệu, kỹ thuật và người chế tác. Khách tham quan có thể nhìn gần bề mặt men và nhận ra những khác biệt chỉ có ở sản phẩm làm thủ công.\n\n' +
          'Sự kiện là một bước tiếp nối trong hành trình đưa gốm Việt đến với công chúng quốc tế bằng chính bản sắc và tiêu chuẩn hoàn thiện của mình.',
      },
      {
        id: 'n4',
        slug: 'workshop-tu-tay-vuot-gom',
        category: 'Hoạt động',
        date: '20 THG 06, 2026',
        title: 'Workshop: Tự tay vuốt gốm cùng nghệ nhân',
        excerpt:
          'Trải nghiệm cảm giác biến khối đất sét vô tri thành tác phẩm nghệ thuật dưới sự hướng dẫn trực tiếp.',
        image: '/assets/news/news-4.jpg',
        author: 'Ban biên tập Gốm Hoa Sen',
        readingTime: '3 phút đọc',
        content:
          'Workshop đưa người tham dự đi qua những thao tác nền tảng: làm mềm đất, định tâm trên bàn xoay, tạo dáng và hoàn thiện bề mặt. Mỗi bước đều có nghệ nhân hướng dẫn trực tiếp.\n\n' +
          'Trải nghiệm thực hành giúp người tham dự hiểu vì sao một dáng gốm cân đối cần sự tập trung, nhịp tay ổn định và nhiều năm rèn luyện.\n\n' +
          'Tác phẩm sau buổi học được xử lý, phủ men và nung hoàn thiện tại xưởng trước khi gửi lại cho người tham dự như một kỷ niệm riêng.',
      },
      {
        id: 'n5',
        slug: 'bi-an-men-lam-truyen-thong',
        category: 'Nghệ thuật gốm',
        date: '12 THG 06, 2026',
        title: 'Bí ẩn đằng sau lớp men Lam truyền thống',
        excerpt:
          'Màu xanh lam đặc trưng được chiết xuất từ quặng tự nhiên mang đến vẻ đẹp vĩnh cửu cho từng tác phẩm.',
        image: '/assets/news/news-5.jpg',
        author: 'Ban biên tập Gốm Hoa Sen',
        readingTime: '4 phút đọc',
        content:
          'Men lam tạo nên sắc xanh có độ sâu đặc biệt trên nền gốm trắng. Từ khâu pha màu đến tốc độ đưa nét cọ, mọi thao tác đều ảnh hưởng đến sắc độ sau khi nung.\n\n' +
          'Ở nhiệt độ cao, màu vẽ thay đổi và hòa vào lớp men phủ. Người nghệ nhân phải hình dung trước kết quả cuối cùng khi bề mặt sản phẩm vẫn còn ở trạng thái mộc.\n\n' +
          'Sự bền bỉ của men lam khiến dòng gốm này phù hợp cả với vật phẩm sử dụng hằng ngày lẫn tác phẩm trưng bày có giá trị lâu dài.',
      },
      {
        id: 'n6',
        slug: 'chuyen-nguoi-tho-lo',
        category: 'Làng nghề',
        date: '01 THG 06, 2026',
        title: 'Chuyện người thợ lò: Những đêm thức trắng canh lửa',
        excerpt:
          'Thành bại của một mẻ gốm phụ thuộc hoàn toàn vào trực giác và đôi mắt nhìn lửa của người thợ già.',
        image: '/assets/news/news-6.jpg',
        author: 'Ban biên tập Gốm Hoa Sen',
        readingTime: '5 phút đọc',
        content:
          'Một mẻ nung kéo dài qua nhiều giờ và không cho phép người thợ lơ là. Màu lửa trong lò, âm thanh của dòng khí và tốc độ tăng nhiệt đều là những tín hiệu phải được theo dõi liên tục.\n\n' +
          'Kinh nghiệm canh lửa hình thành từ rất nhiều mẻ nung thành công lẫn thất bại. Người thợ giỏi biết khi nào cần giữ nhiệt, khi nào cần tăng lửa và thời điểm thích hợp để kết thúc chu trình.\n\n' +
          'Sau khi lò nguội, khoảnh khắc mở cửa lò luôn chứa cả hồi hộp và tự hào. Đó là lúc nhiều ngày lao động được trả lời bằng màu men và hình hài cuối cùng của sản phẩm.',
      },
    ],
  },
  artisans: {
    eyebrow: 'Con người & làng nghề',
    title: 'Nghệ Nhân Gốm Việt',
    desc: 'Gặp gỡ những người đang gìn giữ kỹ nghệ, truyền lửa nghề và tạo nên linh hồn cho từng tác phẩm Gốm Hoa Sen.',
    loadingText: 'Đang tải danh sách nghệ nhân...',
    errorTitle: 'Chưa thể tải hồ sơ nghệ nhân',
    errorText: 'Kết nối đang gián đoạn. Vui lòng thử lại sau ít phút.',
    retryLabel: 'Thử lại',
    emptyText: 'Thông tin nghệ nhân đang được cập nhật.',
    notFoundTitle: 'Không tìm thấy nghệ nhân',
    notFoundBody: 'Hồ sơ bạn tìm kiếm không tồn tại hoặc hiện chưa được công bố.',
    backLabel: 'Quay lại danh sách nghệ nhân',
    profileCtaLabel: 'Xem hồ sơ',
    experienceLabel: 'năm kinh nghiệm',
    bioTitle: 'Tiểu sử',
    lineageTitle: 'Dòng nghề & truyền thống',
    workshopTitle: 'Xưởng gốm',
    certificationsTitle: 'Chứng nhận & danh hiệu',
    contactTitle: 'Liên hệ tư vấn tác phẩm',
    contactBody: 'Trao đổi cùng Gốm Hoa Sen để tìm hiểu tác phẩm và khả năng chế tác theo yêu cầu.',
    phoneCtaLabel: 'Gọi tư vấn',
    emailCtaLabel: 'Gửi email',
  },
  contact: {
    heroTitle: 'Ghé Thăm Showroom',
    heroDesc: 'Nơi tinh hoa hội tụ. Chào mừng quý khách đến với không gian thưởng lãm nghệ thuật Gốm Hoa Sen.',
    openingHours: 'Thứ 2 - Chủ Nhật\n8:00 - 20:00',
    locationBandImage: '/assets/contact/contact-location.jpg',
    mapCtaLabel: 'CHỈ ĐƯỜNG',
    mapCtaHref: 'https://maps.google.com/?q=Số+41+Giang+Cao,+Bát+Tràng,+Hà+Nội',
    heroBg: '/assets/contact/contact-hero.jpg',
    formTitle: 'Gửi Thông Điệp',
    submitLabel: 'Gửi thông điệp',
    submittingLabel: 'Đang gửi...',
    successMessage: 'Cảm ơn bạn đã liên hệ!\nChúng tôi sẽ phản hồi trong thời gian sớm nhất.',
    successResetLabel: 'Gửi yêu cầu khác',
    errorMessage: 'Chưa gửi được yêu cầu. Vui lòng thử lại.',
    namePlaceholder: 'Họ và tên *',
    phonePlaceholder: 'Số điện thoại *',
    emailPlaceholder: 'Email',
    notePlaceholder: 'Nội dung liên hệ *',
    showroomLabel: 'Showroom',
    hotlineLabel: 'Hotline',
    openingHoursLabel: 'Giờ mở cửa',
    emailLabel: 'Email',
    locationImageAlt: 'Mặt tiền Showroom',
  },
  catalog: {
    listingEyebrow: 'Gốm Hoa Sen Collection',
    listingTitle: 'Bộ sưu tập gốm sứ',
    listingSubtitle: 'Những tác phẩm gốm được tuyển chọn theo chất men, hoa văn, công năng và không gian sống.',
    listingAdvisorTitle: 'Chưa biết chọn mẫu nào?',
    listingAdvisorBody: 'Cho chúng tôi biết không gian, ngân sách hoặc mục đích tặng để được gợi ý bộ gốm sứ phù hợp.',
    listingLoadingText: 'Đang tải danh mục sản phẩm...',
    listingErrorText: 'Chưa tải được danh mục sản phẩm. Vui lòng thử lại.',
    listingRetryLabel: 'Thử tải lại',
    detailLoadingText: 'Đang tải chi tiết sản phẩm...',
    detailErrorText: 'Chưa tải được chi tiết sản phẩm. Vui lòng thử lại.',
    detailNotFoundText: 'Sản phẩm bạn tìm kiếm hiện không còn hiển thị.',
    detailCtaLabel: 'Tư vấn & Đặt hàng',
    detailBackLabel: 'Xem danh mục sản phẩm',
    listingLabels: {
      featured360Label: 'Xem sản phẩm 360°',
      exploreLabel: 'Khám phá sản phẩm',
      productCountLabel: 'sản phẩm',
      collectionCountLabel: 'bộ sưu tập',
      glazeCountLabel: 'dòng men',
      filterTitle: 'Bộ lọc',
      resetLabel: 'Đặt lại',
      collectionFilterLabel: 'Bộ sưu tập',
      typeFilterLabel: 'Loại sản phẩm',
      glazeFilterLabel: 'Dòng men',
      priceFilterLabel: 'Khoảng giá',
      statusFilterLabel: 'Trạng thái',
      status360Label: 'Có trải nghiệm 360°',
      statusNewLabel: 'Sản phẩm mới',
      statusLimitedLabel: 'Phiên bản giới hạn',
      statusBestSellerLabel: 'Bán chạy',
      sortLabel: 'Sắp xếp:',
      sortFeaturedLabel: 'Nổi bật',
      sortNewestLabel: 'Mới nhất',
      sortPriceAscLabel: 'Giá thấp → cao',
      sortPriceDescLabel: 'Giá cao → thấp',
      sort360Label: 'Có 360° trước',
      badgeNewLabel: 'Mới',
      badgeLimitedLabel: 'Giới hạn',
      badgeBestSellerLabel: 'Bán chạy',
      quickViewLabel: 'Xem nhanh',
      experience360Label: 'Trải nghiệm 360°',
      detailLabel: 'Xem chi tiết',
      emptyTitle: 'Không tìm thấy sản phẩm',
      emptyBody: 'Thử thay đổi bộ lọc hoặc',
      emptyResetLabel: 'Đặt lại tất cả',
      advisorCtaLabel: 'Nhận tư vấn miễn phí →',
      applyFilterLabel: 'Áp dụng',
      consultationLabel: 'Tư vấn ngay',
      footerTemplate: '© {year} {brand}. Tất cả quyền được bảo lưu.',
    },
    detailLabels: {
      loadingSubtitle: 'Đang tải trải nghiệm 3D',
      specsTitle: 'Thông số kỹ thuật',
      contactTitle: 'Tư vấn & Đặt hàng',
      directChatLabel: 'Chat trực tiếp',
      namePlaceholder: 'Họ tên',
      phonePlaceholder: 'Số điện thoại',
      emailPlaceholder: 'Email (tùy chọn)',
      notePlaceholder: 'Ghi chú (tùy chọn)',
      submitLabel: 'Gửi yêu cầu tư vấn',
      submittingLabel: 'Đang gửi...',
      successTemplate: 'Cảm ơn {name}! Đội ngũ Gốm Hoa Sen sẽ liên hệ sớm.',
      errorMessage: 'Chưa gửi được yêu cầu. Vui lòng thử lại.',
      view360Title: 'Trải nghiệm 360°',
      view360Note: 'Nội dung chỉ được tải sau khi bạn bấm xem, không tự phát trước khi tương tác.',
      exit3dLabel: 'Thoát 3D',
      fullscreen3dLabel: 'Xem 3D toàn màn hình',
      productInfoLabel: 'Xem thông tin tác phẩm',
      imageUpdatingLabel: 'Hình ảnh đang được cập nhật',
      imageLabel: 'Hình',
      viewLabel: 'Góc nhìn',
      interact3dLabel: 'Tương tác 3D toàn màn hình',
      video360Label: 'Xem Video 360°',
      variantsTitle: 'Biến thể tác phẩm',
      storyTitle: 'Câu chuyện chế tác',
      zaloLabel: 'Zalo Chat',
      hotlineLabel: 'Gọi Hotline',
      emailLabel: 'Gửi Email',
      rfqTitle: 'Yêu cầu báo giá tác phẩm',
      shortcutVariantLabel: 'Biến thể',
      shortcutStoryLabel: 'Câu chuyện',
      shortcutSpecsLabel: 'Thông số',
      shortcutContactLabel: 'Tư vấn',
    },
  },
};

export function createShowroomV2DefaultContent(): ShowroomV2ContentContract {
  return JSON.parse(JSON.stringify(SHOWROOM_V2_DEFAULT_CONTENT)) as ShowroomV2ContentContract;
}
