/**
 * @vt/voucher-core — Shared voucher contracts and validation rules.
 */

export {
  DEFAULT_VOUCHER_STATUS,
  VOUCHER_ANALYTICS,
  VOUCHER_ACTIVE_TIMING_STATUSES,
  VOUCHER_BULK_REJECTION_REASONS,
  VOUCHER_CONSTANTS,
  VOUCHER_ELIGIBILITY,
  VOUCHER_EXPIRED_TIMING_STATUSES,
  VOUCHER_LIMITS,
  VOUCHER_PAGINATION,
  VOUCHER_PUBLIC_ERROR_MESSAGES,
  VOUCHER_REDEMPTION_STATUSES,
  VOUCHER_REDEMPTION_STATUS_VALUES,
  VOUCHER_USER_ERROR_REASONS,
  VOUCHER_VALIDATION_ERROR_REASONS,
  VOUCHER_VALIDATION_MESSAGES,
  VOUCHER_STATUSES,
  VOUCHER_STATUS_VALUES,
  VOUCHER_TYPES,
  VOUCHER_TYPE_VALUES,
  type VoucherType,
  type VoucherStatus,
  type VoucherRedemptionStatus,
  type IVoucherRedemptionRecord,
  type IVoucher,
  type VoucherValidationResult,
  type VoucherInvalidReason,
  type VoucherCreateError,
  type VoucherRules,
  VOUCHER_INVALID_REASONS,
  VOUCHER_CREATE_ERRORS,
  DEFAULT_VOUCHER_RULES,
  isActiveVoucherStatus,
  isExpiredVoucherStatus,
  isVoucherRedemptionStatus,
  isVoucherStatus,
  isVoucherType,
  readVoucherRedemptionStatus,
  readVoucherStatus,
  readVoucherType,
  voucherInvalidNumericFieldMessage,
} from './lib/voucher.contracts';

export {
  validateVoucher,
  getVoucherInvalidReason,
  validateVoucherRuntime,
  type VoucherRuntimeCartItem,
  type VoucherRuntimeSnapshot,
  type VoucherRuntimeValidationInput,
  type VoucherRuntimeValidationReasonMap,
  type VoucherRuntimeValidationResult,
} from './lib/voucher-validation.helper';
