/**
 * Quote Error Constants
 *
 * Zalo ref: libs/catalog/src/lib/constants/catalog.constants.ts
 */
export const QUOTE_ERRORS = {
  QUOTE_NOT_FOUND: 'QUOTE_NOT_FOUND',
  QUOTE_ALREADY_SENT: 'QUOTE_ALREADY_SENT',
  QUOTE_ITEMS_REQUIRED: 'QUOTE_ITEMS_REQUIRED',
  QUOTE_INVALID_LINE_ITEM: 'QUOTE_INVALID_LINE_ITEM',
  QUOTE_INVALID_STATUS_TRANSITION: 'QUOTE_INVALID_STATUS_TRANSITION',
  QUOTE_COUNTER_FAILED: 'QUOTE_COUNTER_FAILED',
} as const;
