export const ORDER_ERRORS = {
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_INVALID_STATUS_TRANSITION: 'ORDER_INVALID_STATUS_TRANSITION',
  ORDER_EMPTY_LINE_ITEMS: 'ORDER_EMPTY_LINE_ITEMS',
} as const;
