export const MEMBERSHIP_UPGRADE_REQUEST_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
} as const;

export type MembershipUpgradeRequestStatus =
  typeof MEMBERSHIP_UPGRADE_REQUEST_STATUS[keyof typeof MEMBERSHIP_UPGRADE_REQUEST_STATUS];

export const UPGRADE_REQUEST_STATUS = MEMBERSHIP_UPGRADE_REQUEST_STATUS;

export type UpgradeRequestStatus =
  typeof UPGRADE_REQUEST_STATUS[keyof typeof UPGRADE_REQUEST_STATUS];

export const MEMBERSHIP_UPGRADE_REQUEST_REVIEWABLE_STATUSES = [
  MEMBERSHIP_UPGRADE_REQUEST_STATUS.APPROVED,
  MEMBERSHIP_UPGRADE_REQUEST_STATUS.REJECTED,
] as const;

export type MembershipUpgradeRequestReviewAction =
  (typeof MEMBERSHIP_UPGRADE_REQUEST_REVIEWABLE_STATUSES)[number];

export const MEMBERSHIP_UPGRADE_REQUEST_SOURCE_REASON = {
  AUTO_QUALIFIED: 'AUTO_QUALIFIED',
  MANUAL_SUBMIT: 'MANUAL_SUBMIT',
  ADMIN_REQUEST: 'ADMIN_REQUEST',
} as const;

export type MembershipUpgradeRequestSourceReason =
  typeof MEMBERSHIP_UPGRADE_REQUEST_SOURCE_REASON[keyof typeof MEMBERSHIP_UPGRADE_REQUEST_SOURCE_REASON];

export const UPGRADE_REQUEST_SOURCE = MEMBERSHIP_UPGRADE_REQUEST_SOURCE_REASON;

export type UpgradeRequestSource =
  typeof UPGRADE_REQUEST_SOURCE[keyof typeof UPGRADE_REQUEST_SOURCE];

export const TIER_PROJECTION_STATUS = {
  CURRENT: 'CURRENT',
  NEXT: 'NEXT',
  LOCKED: 'LOCKED',
  ELIGIBLE: 'ELIGIBLE',
} as const;

export type TierProjectionStatus =
  typeof TIER_PROJECTION_STATUS[keyof typeof TIER_PROJECTION_STATUS];

export const TIER_PUBLICATION_REVISION_STATUS = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  DISCARDED: 'DISCARDED',
  ROLLED_BACK: 'ROLLED_BACK',
} as const;

export type PublicationRevisionStatus =
  typeof TIER_PUBLICATION_REVISION_STATUS[keyof typeof TIER_PUBLICATION_REVISION_STATUS];

export const TIER_PUBLICATION_HISTORY_STATUSES = [
  TIER_PUBLICATION_REVISION_STATUS.PUBLISHED,
  TIER_PUBLICATION_REVISION_STATUS.ROLLED_BACK,
  TIER_PUBLICATION_REVISION_STATUS.DISCARDED,
] as const;

export const TIER_PUBLICATION_ROLLBACK_SOURCE_STATUSES = [
  TIER_PUBLICATION_REVISION_STATUS.PUBLISHED,
  TIER_PUBLICATION_REVISION_STATUS.ROLLED_BACK,
] as const;
