/** Catalog domain error codes */
export const CATALOG_ERROR_CODES = {
  PRODUCT_NOT_FOUND: 'CATALOG_PRODUCT_NOT_FOUND',
  CATEGORY_NOT_FOUND: 'CATALOG_CATEGORY_NOT_FOUND',
  VARIANT_NOT_FOUND: 'CATALOG_VARIANT_NOT_FOUND',
  TEMPLATE_NOT_FOUND: 'CATALOG_TEMPLATE_NOT_FOUND',
  BRAND_NOT_FOUND: 'CATALOG_BRAND_NOT_FOUND',
  PRODUCT_INVALID_DATA: 'CATALOG_PRODUCT_INVALID_DATA',
  SKU_ALREADY_EXISTS: 'CATALOG_SKU_ALREADY_EXISTS',
  PRODUCT_ALREADY_PUBLISHED: 'CATALOG_PRODUCT_ALREADY_PUBLISHED',
  CATALOG_TENANT_MISMATCH: 'CATALOG_TENANT_MISMATCH',
} as const;

export type CatalogErrorCode = (typeof CATALOG_ERROR_CODES)[keyof typeof CATALOG_ERROR_CODES];
