/** Enablement domain error codes — module activation, business types, tenant enablement */
export const ENABLEMENT_ERROR_CODES = {
  // ── Entity not found ──
  BUSINESS_TYPE_NOT_FOUND: 'BUSINESS_TYPE_NOT_FOUND',
  MODULE_NOT_FOUND: 'MODULE_NOT_FOUND',

  // ── Validation errors ──
  INVALID_ACTIVATION_DATA: 'INVALID_ACTIVATION_DATA',
  TENANT_VARIABLE_INVALID_FIELD_VALUE: 'TENANT_VARIABLE_INVALID_FIELD_VALUE',

  // ── State conflict ──
  MODULE_ALREADY_ENABLED: 'MODULE_ALREADY_ENABLED',
  MODULE_ALREADY_DISABLED: 'MODULE_ALREADY_DISABLED',

  // ── Authorization & tenant context ──
  ENABLEMENT_TENANT_MISMATCH: 'ENABLEMENT_TENANT_MISMATCH',
  PLATFORM_TENANT_REQUIRED: 'PLATFORM_TENANT_REQUIRED',
  TENANT_CONTEXT_MISSING: 'TENANT_CONTEXT_MISSING',

  // ── Dependency ──
  CONTRACT_MAPPING_FAILED: 'CONTRACT_MAPPING_FAILED',
  TENANT_ENABLEMENT_NOT_FOUND: 'TENANT_ENABLEMENT_NOT_FOUND',
  TENANT_VARIABLE_UPSERT_INVARIANT_FAILED: 'TENANT_VARIABLE_UPSERT_INVARIANT_FAILED',
} as const;

export type EnablementErrorCode = (typeof ENABLEMENT_ERROR_CODES)[keyof typeof ENABLEMENT_ERROR_CODES];
