/** Fields domain error codes — custom fields, field sets, option sets */
export const FIELDS_ERROR_CODES = {
  // ── Entity not found ──
  FIELD_NOT_FOUND: 'FIELD_NOT_FOUND',
  FIELD_BLOCK_NOT_FOUND: 'FIELD_BLOCK_NOT_FOUND',
  FIELD_SET_NOT_FOUND: 'FIELD_SET_NOT_FOUND',
  OPTION_SET_NOT_FOUND: 'OPTION_SET_NOT_FOUND',

  // ── Validation errors ──
  FIELD_INVALID_DATA: 'FIELD_INVALID_DATA',
  FIELD_KEY_ALREADY_EXISTS: 'FIELD_KEY_ALREADY_EXISTS',
  FIELD_KEY_COUNTER_SEQUENCE_INVALID: 'FIELD_KEY_COUNTER_SEQUENCE_INVALID',
  FIELD_UNKNOWN_DATA_TYPE: 'FIELD_UNKNOWN_DATA_TYPE',
  FIELD_UPDATE_NOT_DRAFT: 'FIELD_UPDATE_NOT_DRAFT',
  FIELD_REVISE_REQUIRES_PUBLISHED: 'FIELD_REVISE_REQUIRES_PUBLISHED',
  FIELD_PUBLISH_REQUIRES_DRAFT: 'FIELD_PUBLISH_REQUIRES_DRAFT',
  FIELD_SYSTEM_DEPRECATE_FORBIDDEN: 'FIELD_SYSTEM_DEPRECATE_FORBIDDEN',
  FIELD_DEPRECATE_REQUIRES_PUBLISHED: 'FIELD_DEPRECATE_REQUIRES_PUBLISHED',
  FIELD_SYSTEM_DELETE_FORBIDDEN: 'FIELD_SYSTEM_DELETE_FORBIDDEN',
  FIELD_DELETE_REQUIRES_DRAFT: 'FIELD_DELETE_REQUIRES_DRAFT',
  FIELD_INTERNAL_UPDATE_NOT_DRAFT: 'FIELD_INTERNAL_UPDATE_NOT_DRAFT',
  FIELD_BLOCK_UPDATE_NOT_DRAFT: 'FIELD_BLOCK_UPDATE_NOT_DRAFT',
  FIELD_BLOCK_REVISE_REQUIRES_PUBLISHED: 'FIELD_BLOCK_REVISE_REQUIRES_PUBLISHED',
  FIELD_BLOCK_PUBLISH_REQUIRES_DRAFT: 'FIELD_BLOCK_PUBLISH_REQUIRES_DRAFT',
  FIELD_BLOCK_DEPRECATE_REQUIRES_PUBLISHED: 'FIELD_BLOCK_DEPRECATE_REQUIRES_PUBLISHED',
  FIELD_BLOCK_DELETE_REQUIRES_DRAFT: 'FIELD_BLOCK_DELETE_REQUIRES_DRAFT',
  FIELD_SET_KEY_ALREADY_EXISTS: 'FIELD_SET_KEY_ALREADY_EXISTS',
  FIELD_SET_REORDER_UNKNOWN_FIELD_KEYS: 'FIELD_SET_REORDER_UNKNOWN_FIELD_KEYS',
  FIELDS_PAGINATION_QUERY_INVALID: 'FIELDS_PAGINATION_QUERY_INVALID',
  OPTION_SET_UPDATE_NOT_DRAFT: 'OPTION_SET_UPDATE_NOT_DRAFT',
  OPTION_SET_REVISE_REQUIRES_PUBLISHED: 'OPTION_SET_REVISE_REQUIRES_PUBLISHED',
  OPTION_SET_PUBLISH_REQUIRES_DRAFT: 'OPTION_SET_PUBLISH_REQUIRES_DRAFT',
  OPTION_SET_DEPRECATE_REQUIRES_PUBLISHED: 'OPTION_SET_DEPRECATE_REQUIRES_PUBLISHED',
  OPTION_SET_DELETE_REQUIRES_DRAFT: 'OPTION_SET_DELETE_REQUIRES_DRAFT',
  OPTION_SET_STATUS_REQUIRES_ONE_OPEN: 'OPTION_SET_STATUS_REQUIRES_ONE_OPEN',
  OPTION_SET_STATUS_REQUIRES_ONE_DONE: 'OPTION_SET_STATUS_REQUIRES_ONE_DONE',
  OPTION_SET_STATUS_OPEN_VALUE_IMMUTABLE: 'OPTION_SET_STATUS_OPEN_VALUE_IMMUTABLE',
  OPTION_SET_STATUS_DONE_VALUE_IMMUTABLE: 'OPTION_SET_STATUS_DONE_VALUE_IMMUTABLE',
  OPTION_SET_REFERENCED_VALUES: 'OPTION_SET_REFERENCED_VALUES',
  FIELDS_TENANT_CONTEXT_MISSING: 'FIELDS_TENANT_CONTEXT_MISSING',
  FIELDS_PARTY_CONTEXT_MISSING: 'FIELDS_PARTY_CONTEXT_MISSING',

  // ── Authorization ──
  FIELDS_UNAUTHORIZED: 'FIELDS_UNAUTHORIZED',
  FIELD_TENANT_MISMATCH: 'FIELD_TENANT_MISMATCH',
  FIELDS_CLIENT_SCOPE_UNSUPPORTED: 'FIELDS_CLIENT_SCOPE_UNSUPPORTED',
  FIELDS_CLIENT_ENTITY_ACCESS_DENIED: 'FIELDS_CLIENT_ENTITY_ACCESS_DENIED',

  // ── Generic fallbacks ──
  GENERIC_BAD_REQUEST: 'FIELDS_GENERIC_BAD_REQUEST',
  GENERIC_NOT_FOUND: 'FIELDS_GENERIC_NOT_FOUND',
  GENERIC_CONFLICT: 'FIELDS_GENERIC_CONFLICT',
  GENERIC_FORBIDDEN: 'FIELDS_GENERIC_FORBIDDEN',
  GENERIC_INTERNAL: 'FIELDS_GENERIC_INTERNAL',
} as const;

export type FieldsErrorCode = (typeof FIELDS_ERROR_CODES)[keyof typeof FIELDS_ERROR_CODES];
