/** File management domain error codes — files, folders, migrations, storage */
export const FILE_ERROR_CODES = {
  // ── Entity not found ──
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FOLDER_NOT_FOUND: 'FOLDER_NOT_FOUND',
  MIGRATION_NOT_FOUND: 'MIGRATION_NOT_FOUND',

  // ── Validation errors ──
  FILE_INVALID_TYPE: 'FILE_INVALID_TYPE',
  FILE_INVALID_OBJECT_ID: 'FILE_INVALID_OBJECT_ID',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_NAME_EMPTY: 'FILE_NAME_EMPTY',
  FILE_FOLDER_NAME_EMPTY: 'FILE_FOLDER_NAME_EMPTY',
  FILE_FOLDER_NAME_PATH_SEPARATOR: 'FILE_FOLDER_NAME_PATH_SEPARATOR',
  FILE_FOLDER_NAME_INVALID: 'FILE_FOLDER_NAME_INVALID',
  FILE_FOLDER_NAME_UNSUPPORTED_CHARS: 'FILE_FOLDER_NAME_UNSUPPORTED_CHARS',
  FILE_FOLDER_PATH_TOO_LONG: 'FILE_FOLDER_PATH_TOO_LONG',
  FILE_TOKEN_QUOTA_EXCEEDED: 'FILE_TOKEN_QUOTA_EXCEEDED',
  FILE_LOCAL_QUOTA_EXCEEDED: 'FILE_LOCAL_QUOTA_EXCEEDED',
  FILE_UPLOAD_PAYLOAD_MISMATCH: 'FILE_UPLOAD_PAYLOAD_MISMATCH',
  FILE_UPLOAD_POLICY_VIOLATION: 'FILE_UPLOAD_POLICY_VIOLATION',
  FILE_INTERNAL_PAYLOAD_INVALID: 'FILE_INTERNAL_PAYLOAD_INVALID',
  FILE_MISSING_UPLOAD_PAYLOAD: 'FILE_MISSING_UPLOAD_PAYLOAD',
  FILE_ACTOR_FIELDS_BACKFILL_REQUIRED: 'FILE_ACTOR_FIELDS_BACKFILL_REQUIRED',
  FILE_MISSING_COMMIT_REF_ATTACHMENTS: 'FILE_MISSING_COMMIT_REF_ATTACHMENTS',
  FILE_MISSING_CUSTOMER_UNREF_SCOPE: 'FILE_MISSING_CUSTOMER_UNREF_SCOPE',
  FILE_MISSING_TENANT_ID: 'FILE_MISSING_TENANT_ID',
  FILE_MIGRATION_RETRY_LIMIT_REQUIRED: 'FILE_MIGRATION_RETRY_LIMIT_REQUIRED',

  // ── State conflict ──
  FILE_QUARANTINED: 'FILE_QUARANTINED',
  FILE_ALREADY_DELETED: 'FILE_ALREADY_DELETED',
  FILE_FOLDER_ALREADY_EXISTS: 'FILE_FOLDER_ALREADY_EXISTS',
  FILE_TENANT_ENTITLEMENT_SET_FAILED: 'FILE_TENANT_ENTITLEMENT_SET_FAILED',
  FILE_TENANT_POLICY_SET_FAILED: 'FILE_TENANT_POLICY_SET_FAILED',
  FILE_UPLOAD_SESSION_EXPIRED: 'FILE_UPLOAD_SESSION_EXPIRED',
  FILE_UPLOAD_SESSION_NOT_WRITABLE: 'FILE_UPLOAD_SESSION_NOT_WRITABLE',

  // ── Authorization ──
  FILE_TENANT_MISMATCH: 'FILE_TENANT_MISMATCH',
  FILE_CUSTOMER_SCOPE_DENIED: 'FILE_CUSTOMER_SCOPE_DENIED',

  // ── External service ──
  STORAGE_PROVIDER_ERROR: 'STORAGE_PROVIDER_ERROR',
  FILE_PROVIDER_UNSUPPORTED: 'FILE_PROVIDER_UNSUPPORTED',

  // ── Upload/session/storage ──
  FILE_DIRECT_LOCAL_UPLOAD_PROVIDER_REQUIRED: 'FILE_DIRECT_LOCAL_UPLOAD_PROVIDER_REQUIRED',
  FILE_REFERENCE_EXTERNAL_URL_REQUIRED: 'FILE_REFERENCE_EXTERNAL_URL_REQUIRED',
  FILE_SHARE_CREDENTIAL_PAIR_REQUIRED: 'FILE_SHARE_CREDENTIAL_PAIR_REQUIRED',
  FILE_SHARE_LINK_EXPIRED: 'FILE_SHARE_LINK_EXPIRED',
  FILE_SHARE_LINK_MAX_DOWNLOADS_EXCEEDED: 'FILE_SHARE_LINK_MAX_DOWNLOADS_EXCEEDED',
  FILE_SHARE_LINK_NOT_FOUND: 'FILE_SHARE_LINK_NOT_FOUND',
  FILE_SHARE_LINK_REVOKED: 'FILE_SHARE_LINK_REVOKED',
  FILE_STORAGE_KEY_REQUIRED: 'FILE_STORAGE_KEY_REQUIRED',
  FILE_TOKEN_QUERY_REQUIRED: 'FILE_TOKEN_QUERY_REQUIRED',
  FILE_UPLOAD_SESSION_NOT_FOUND: 'FILE_UPLOAD_SESSION_NOT_FOUND',

  // ── Generic fallbacks ──
  GENERIC_BAD_REQUEST: 'FILE_GENERIC_BAD_REQUEST',
  GENERIC_NOT_FOUND: 'FILE_GENERIC_NOT_FOUND',
  GENERIC_CONFLICT: 'FILE_GENERIC_CONFLICT',
  GENERIC_FORBIDDEN: 'FILE_GENERIC_FORBIDDEN',
  GENERIC_INTERNAL: 'FILE_GENERIC_INTERNAL',
} as const;

export type FileErrorCode = (typeof FILE_ERROR_CODES)[keyof typeof FILE_ERROR_CODES];
