/** IAM domain error codes — auth, member, user */
export const IAM_ERROR_CODES = {
  // ── Auth ──
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_INVALID_HEADER: 'AUTH_INVALID_HEADER',
  AUTH_EXPIRED_TOKEN: 'AUTH_EXPIRED_TOKEN',
  AUTH_MISSING_TOKEN: 'AUTH_MISSING_TOKEN',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  IAM_UNAUTHORIZED: 'IAM_UNAUTHORIZED',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  IAM_INVALID_TOKEN_TYPE: 'IAM_INVALID_TOKEN_TYPE',
  IAM_TENANT_CONTEXT_MISSING: 'IAM_TENANT_CONTEXT_MISSING',
  IAM_TENANT_CONTEXT_MISMATCH: 'IAM_TENANT_CONTEXT_MISMATCH',

  // ── Member (VITA) ──
  MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',
  MEMBER_LOCKED: 'MEMBER_LOCKED',
  MEMBER_DUPLICATE_PHONE: 'MEMBER_DUPLICATE_PHONE',
  MEMBER_INVALID_REFERRAL: 'MEMBER_INVALID_REFERRAL',
  MEMBER_SELF_REFERRAL: 'MEMBER_SELF_REFERRAL',
  MEMBER_SCOPE_VIOLATION: 'MEMBER_SCOPE_VIOLATION',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',

  // ── User (3d) ──
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_DUPLICATE_EMAIL: 'USER_DUPLICATE_EMAIL',
  USER_INVALID_ROLE: 'USER_INVALID_ROLE',

  // ── File/Upload ──
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_TYPE_NOT_ALLOWED: 'FILE_TYPE_NOT_ALLOWED',
  FILE_SIZE_EXCEEDED: 'FILE_SIZE_EXCEEDED',
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',

  // ── Service Ticket (VITA CSSK) ──
  TICKET_NOT_FOUND: 'TICKET_NOT_FOUND',
  TICKET_INVALID_TRANSITION: 'TICKET_INVALID_TRANSITION',
  TICKET_ALREADY_RESOLVED: 'TICKET_ALREADY_RESOLVED',

  // ── Store / POS (VITA) ──
  STORE_NOT_FOUND: 'STORE_NOT_FOUND',
  STORE_ACCESS_DENIED: 'STORE_ACCESS_DENIED',
  STORE_EMPLOYEE_NOT_FOUND: 'STORE_EMPLOYEE_NOT_FOUND',
  STORE_EMPLOYEE_ALREADY_ASSIGNED: 'STORE_EMPLOYEE_ALREADY_ASSIGNED',
  STORE_EMPLOYEE_NAME_REQUIRED: 'STORE_EMPLOYEE_NAME_REQUIRED',
  STORE_SETTINGS_REQUIRED_FIELD: 'STORE_SETTINGS_REQUIRED_FIELD',
  STORE_SETTINGS_INVALID_TIME: 'STORE_SETTINGS_INVALID_TIME',
  STORE_SETTINGS_INVALID_TIME_RANGE: 'STORE_SETTINGS_INVALID_TIME_RANGE',
  STORE_BILL_NOT_FOUND: 'STORE_BILL_NOT_FOUND',
  STORE_BILL_INVALID_AMOUNT: 'STORE_BILL_INVALID_AMOUNT',

  // ── Withdrawal (VITA) ──
  WITHDRAWAL_INSUFFICIENT_BALANCE: 'WITHDRAWAL_INSUFFICIENT_BALANCE',
  WITHDRAWAL_BELOW_MINIMUM: 'WITHDRAWAL_BELOW_MINIMUM',
  WITHDRAWAL_NOT_ELIGIBLE: 'WITHDRAWAL_NOT_ELIGIBLE',
  WITHDRAWAL_NOT_FOUND: 'WITHDRAWAL_NOT_FOUND',
  WITHDRAWAL_INVALID_TRANSITION: 'WITHDRAWAL_INVALID_TRANSITION',

  // ── Area / Reporting (VITA) ──
  AREA_NOT_FOUND: 'AREA_NOT_FOUND',

  // ── Catalog / Artisan (3d) ──
  PRODUCT_CATEGORY_NOT_FOUND: 'PRODUCT_CATEGORY_NOT_FOUND',
  ARTISAN_NOT_FOUND: 'ARTISAN_NOT_FOUND',
  PROVENANCE_NOT_FOUND: 'PROVENANCE_NOT_FOUND',
  SITE_CONFIG_NOT_FOUND: 'SITE_CONFIG_NOT_FOUND',
} as const;

export type IamErrorCode = (typeof IAM_ERROR_CODES)[keyof typeof IAM_ERROR_CODES];
