/** Loyalty domain error codes — membership, rank upgrade, score, points, redeem, publication */
export const LOYALTY_ERROR_CODES = {
  // ── Shared Loyalty Boundary ──
  LOYALTY_INTERNAL_ERROR: 'LOYALTY_INTERNAL_ERROR',
  LOYALTY_INVALID_OBJECT_ID: 'LOYALTY_INVALID_OBJECT_ID',
  INTERNAL_STATE_PAYLOAD_INVALID: 'INTERNAL_STATE_PAYLOAD_INVALID',
  INTERNAL_REQUIRED_FIELD_MISSING: 'INTERNAL_REQUIRED_FIELD_MISSING',
  INTERNAL_PAYLOAD_INVALID: 'INTERNAL_PAYLOAD_INVALID',
  INTERNAL_COLLECTION_INVALID: 'INTERNAL_COLLECTION_INVALID',
  LOYALTY_QUERY_POSITIVE_INTEGER_REQUIRED: 'LOYALTY_QUERY_POSITIVE_INTEGER_REQUIRED',
  LOYALTY_QUERY_LIMIT_MAX_EXCEEDED: 'LOYALTY_QUERY_LIMIT_MAX_EXCEEDED',

  // ── Rank Upgrade ──
  RANK_UPGRADE_NOT_FOUND: 'RANK_UPGRADE_NOT_FOUND',
  RANK_UPGRADE_INVALID_LEVEL: 'RANK_UPGRADE_INVALID_LEVEL',
  RANK_UPGRADE_ALREADY_AT_TARGET: 'RANK_UPGRADE_ALREADY_AT_TARGET',
  RANK_UPGRADE_INVALID_TRANSITION: 'RANK_UPGRADE_INVALID_TRANSITION',
  RANK_UPGRADE_PENDING_EXISTS: 'RANK_UPGRADE_PENDING_EXISTS',

  // ── Score / Points ──
  SCORE_INSUFFICIENT_BALANCE: 'SCORE_INSUFFICIENT_BALANCE',
  SCORE_TRANSFER_SELF: 'SCORE_TRANSFER_SELF',
  SCORE_TRANSFER_INVALID_AMOUNT: 'SCORE_TRANSFER_INVALID_AMOUNT',
  SCORE_NEGATIVE_AMOUNT: 'SCORE_NEGATIVE_AMOUNT',

  // ── Redeem ──
  REDEEM_INSUFFICIENT_FUNDS: 'REDEEM_INSUFFICIENT_FUNDS',
  REDEEM_PROGRAM_DISABLED: 'REDEEM_PROGRAM_DISABLED',
  REDEEM_CATALOG_ITEM_NOT_FOUND: 'REDEEM_CATALOG_ITEM_NOT_FOUND',
  REDEEM_OUT_OF_STOCK: 'REDEEM_OUT_OF_STOCK',
  REDEEM_INVALID_STEP: 'REDEEM_INVALID_STEP',
  REDEEM_BELOW_MINIMUM: 'REDEEM_BELOW_MINIMUM',
  REDEEM_WALLET_DEBIT_FAILED: 'REDEEM_WALLET_DEBIT_FAILED',

  // ── Publication Draft / Tier ──
  PUBLICATION_DRAFT_NOT_FOUND: 'PUBLICATION_DRAFT_NOT_FOUND',
  PUBLICATION_REVISION_NOT_FOUND: 'PUBLICATION_REVISION_NOT_FOUND',
  PUBLICATION_INVALID_REVISION_ID: 'PUBLICATION_INVALID_REVISION_ID',
  PUBLICATION_EMPTY_TIERS: 'PUBLICATION_EMPTY_TIERS',
  PUBLICATION_INVALID_TIER_ID: 'PUBLICATION_INVALID_TIER_ID',
  PUBLICATION_DUPLICATE_TIER_ID: 'PUBLICATION_DUPLICATE_TIER_ID',
  PUBLICATION_TIER_MISSING_NAME: 'PUBLICATION_TIER_MISSING_NAME',
  PUBLICATION_TIER_MISSING_SLUG: 'PUBLICATION_TIER_MISSING_SLUG',
  PUBLICATION_DUPLICATE_TIER_NAME: 'PUBLICATION_DUPLICATE_TIER_NAME',
  PUBLICATION_DUPLICATE_TIER_SLUG: 'PUBLICATION_DUPLICATE_TIER_SLUG',
  PUBLICATION_TIER_IN_USE: 'PUBLICATION_TIER_IN_USE',
  TIER_NOT_FOUND: 'TIER_NOT_FOUND',
  TIER_NAME_REQUIRED: 'TIER_NAME_REQUIRED',
  TIER_NAME_ALREADY_EXISTS: 'TIER_NAME_ALREADY_EXISTS',
  TIER_INVALID_FIELD_VALUE: 'TIER_INVALID_FIELD_VALUE',

  // ── Condition Evaluator ──
  CONDITION_UNKNOWN_TYPE: 'CONDITION_UNKNOWN_TYPE',
  CONDITION_EVAL_FAILED: 'CONDITION_EVAL_FAILED',
  MEMBERSHIP_CONDITIONS_INVALID: 'MEMBERSHIP_CONDITIONS_INVALID',

  // ── Commission ──
  COMMISSION_ALREADY_CALCULATED: 'COMMISSION_ALREADY_CALCULATED',
  COMMISSION_DISABLED: 'COMMISSION_DISABLED',
} as const;

export type LoyaltyErrorCode = (typeof LOYALTY_ERROR_CODES)[keyof typeof LOYALTY_ERROR_CODES];
