/** Quote/RFQ domain error codes — 3d Gốm Hoa Sen */
export const QUOTE_ERROR_CODES = {
  // ── Quote ──
  QUOTE_NOT_FOUND: 'QUOTE_NOT_FOUND',
  QUOTE_EMPTY_ITEMS: 'QUOTE_EMPTY_ITEMS',
  QUOTE_INVALID_TRANSITION: 'QUOTE_INVALID_TRANSITION',
  QUOTE_COUNTER_FAILED: 'QUOTE_COUNTER_FAILED',
  QUOTE_ALREADY_SENT: 'QUOTE_ALREADY_SENT',
  QUOTE_PDF_GENERATION_FAILED: 'QUOTE_PDF_GENERATION_FAILED',
  QUOTE_EMAIL_SEND_FAILED: 'QUOTE_EMAIL_SEND_FAILED',
  QUOTE_SMTP_NOT_CONFIGURED: 'QUOTE_SMTP_NOT_CONFIGURED',

  // ── RFQ ──
  RFQ_NOT_FOUND: 'RFQ_NOT_FOUND',
  RFQ_INVALID_TRANSITION: 'RFQ_INVALID_TRANSITION',
  RFQ_ALREADY_QUOTED: 'RFQ_ALREADY_QUOTED',
} as const;

export type QuoteErrorCode = (typeof QUOTE_ERROR_CODES)[keyof typeof QUOTE_ERROR_CODES];
