/** Realtime/WebSocket domain error codes */
export const REALTIME_ERROR_CODES = {
  CONNECTION_NOT_FOUND: 'REALTIME_CONNECTION_NOT_FOUND',
  ROOM_NOT_FOUND: 'REALTIME_ROOM_NOT_FOUND',
  INVALID_EVENT_PAYLOAD: 'REALTIME_INVALID_EVENT_PAYLOAD',
  CONNECTION_ALREADY_CLOSED: 'REALTIME_CONNECTION_ALREADY_CLOSED',
  AUTH_TOKEN_MISSING: 'REALTIME_AUTH_TOKEN_MISSING',
  AUTH_TOKEN_INVALID: 'REALTIME_AUTH_TOKEN_INVALID',
  AUTH_SUB_MISSING: 'REALTIME_AUTH_SUB_MISSING',
  AUTH_TENANT_MISSING: 'REALTIME_AUTH_TENANT_MISSING',
  AUTH_USER_NOT_FOUND: 'REALTIME_AUTH_USER_NOT_FOUND',
  AUTH_SERVICE_UNAVAILABLE: 'REALTIME_AUTH_SERVICE_UNAVAILABLE',
  ADAPTER_UNAVAILABLE: 'REALTIME_ADAPTER_UNAVAILABLE',
} as const;

export type RealtimeErrorCode = (typeof REALTIME_ERROR_CODES)[keyof typeof REALTIME_ERROR_CODES];
