import assert from 'node:assert/strict';
import test from 'node:test';

import { VOUCHER_ERROR_CODES, VOUCHER_REQUEST_ERROR_CODES } from './voucher.codes';

test('voucher request error codes remain a stable alias set over the canonical voucher domain codes', () => {
  assert.equal(VOUCHER_REQUEST_ERROR_CODES.TENANT_CONTEXT_MISSING, VOUCHER_ERROR_CODES.VOUCHER_TENANT_CONTEXT_MISSING);
  assert.equal(VOUCHER_REQUEST_ERROR_CODES.PARTY_CONTEXT_MISSING, VOUCHER_ERROR_CODES.VOUCHER_PARTY_CONTEXT_MISSING);
  assert.equal(
    VOUCHER_REQUEST_ERROR_CODES.TENANT_CONTEXT_HEADER_REQUIRED,
    VOUCHER_ERROR_CODES.VOUCHER_TENANT_CONTEXT_HEADER_REQUIRED,
  );
  assert.equal(
    VOUCHER_REQUEST_ERROR_CODES.PUBLIC_USER_VOUCHER_TENANT_CONTEXT_REQUIRED,
    VOUCHER_ERROR_CODES.VOUCHER_PUBLIC_USER_VOUCHER_TENANT_CONTEXT_REQUIRED,
  );
  assert.equal(VOUCHER_REQUEST_ERROR_CODES.INVALID_OBJECT_ID, VOUCHER_ERROR_CODES.VOUCHER_INVALID_OBJECT_ID);
  assert.equal(
    VOUCHER_REQUEST_ERROR_CODES.INVALID_PAGINATION_QUERY,
    VOUCHER_ERROR_CODES.VOUCHER_INVALID_PAGINATION_QUERY,
  );
  assert.equal(VOUCHER_REQUEST_ERROR_CODES.INVALID_NUMERIC_FIELD, VOUCHER_ERROR_CODES.VOUCHER_INVALID_NUMERIC_FIELD);
});
