/** Voucher domain error codes — voucher admin, redemption, and user voucher lanes */
export const VOUCHER_ERROR_CODES = {
  VOUCHER_TENANT_CONTEXT_MISSING: 'VOUCHER_TENANT_CONTEXT_MISSING',
  VOUCHER_PARTY_CONTEXT_MISSING: 'VOUCHER_PARTY_CONTEXT_MISSING',
  VOUCHER_TENANT_CONTEXT_HEADER_REQUIRED: 'VOUCHER_TENANT_CONTEXT_HEADER_REQUIRED',
  VOUCHER_PUBLIC_USER_VOUCHER_TENANT_CONTEXT_REQUIRED: 'VOUCHER_PUBLIC_USER_VOUCHER_TENANT_CONTEXT_REQUIRED',
  VOUCHER_INVALID_OBJECT_ID: 'VOUCHER_INVALID_OBJECT_ID',
  VOUCHER_INVALID_PAGINATION_QUERY: 'VOUCHER_INVALID_PAGINATION_QUERY',
  VOUCHER_INVALID_NUMERIC_FIELD: 'VOUCHER_INVALID_NUMERIC_FIELD',
  VOUCHER_CODE_ALREADY_EXISTS: 'VOUCHER_CODE_ALREADY_EXISTS',
  VOUCHER_BULK_INSERT_CODE_UNRESOLVED: 'VOUCHER_BULK_INSERT_CODE_UNRESOLVED',
  VOUCHER_BULK_CREATE_LIMIT_EXCEEDED: 'VOUCHER_BULK_CREATE_LIMIT_EXCEEDED',
  VOUCHER_INVALID_FOR_REDEMPTION: 'VOUCHER_INVALID_FOR_REDEMPTION',
  VOUCHER_REDEMPTION_REASON_REQUIRED: 'VOUCHER_REDEMPTION_REASON_REQUIRED',
  VOUCHER_LIMIT_REACHED: 'VOUCHER_LIMIT_REACHED',
  VOUCHER_NOT_FOUND: 'VOUCHER_NOT_FOUND',
  VOUCHER_NOT_FOUND_OR_INACTIVE: 'VOUCHER_NOT_FOUND_OR_INACTIVE',
  VOUCHER_USAGE_LIMIT_PER_CUSTOMER_INVALID: 'VOUCHER_USAGE_LIMIT_PER_CUSTOMER_INVALID',
  VOUCHER_MIN_ORDER_VALUE_INVALID: 'VOUCHER_MIN_ORDER_VALUE_INVALID',
  VOUCHER_MIN_QUANTITY_INVALID: 'VOUCHER_MIN_QUANTITY_INVALID',
  VOUCHER_VALUE_INVALID: 'VOUCHER_VALUE_INVALID',
  USER_VOUCHER_EXCEEDS_CREATOR_TIER_LIMIT: 'USER_VOUCHER_EXCEEDS_CREATOR_TIER_LIMIT',
  USER_VOUCHER_CODE_ALREADY_EXISTS: 'USER_VOUCHER_CODE_ALREADY_EXISTS',
  USER_VOUCHER_NOT_FOUND: 'USER_VOUCHER_NOT_FOUND',
  USER_VOUCHER_INVALID_OR_INACTIVE: 'USER_VOUCHER_INVALID_OR_INACTIVE',
  USER_VOUCHER_NO_LONGER_AVAILABLE: 'USER_VOUCHER_NO_LONGER_AVAILABLE',

  // ── Migrated from ECOMMERCE_ERROR_CODES (canonical owner: voucher) ──
  VOUCHER_EXPIRED: 'VOUCHER_EXPIRED',
  VOUCHER_ALREADY_USED: 'VOUCHER_ALREADY_USED',
  VOUCHER_NOT_APPLICABLE: 'VOUCHER_NOT_APPLICABLE',
  VOUCHER_INVALID_CODE: 'VOUCHER_INVALID_CODE',
} as const;

export type VoucherErrorCode = (typeof VOUCHER_ERROR_CODES)[keyof typeof VOUCHER_ERROR_CODES];

export const VOUCHER_REQUEST_ERROR_CODES = {
  TENANT_CONTEXT_MISSING: VOUCHER_ERROR_CODES.VOUCHER_TENANT_CONTEXT_MISSING,
  PARTY_CONTEXT_MISSING: VOUCHER_ERROR_CODES.VOUCHER_PARTY_CONTEXT_MISSING,
  TENANT_CONTEXT_HEADER_REQUIRED: VOUCHER_ERROR_CODES.VOUCHER_TENANT_CONTEXT_HEADER_REQUIRED,
  PUBLIC_USER_VOUCHER_TENANT_CONTEXT_REQUIRED:
    VOUCHER_ERROR_CODES.VOUCHER_PUBLIC_USER_VOUCHER_TENANT_CONTEXT_REQUIRED,
  INVALID_OBJECT_ID: VOUCHER_ERROR_CODES.VOUCHER_INVALID_OBJECT_ID,
  INVALID_PAGINATION_QUERY: VOUCHER_ERROR_CODES.VOUCHER_INVALID_PAGINATION_QUERY,
  INVALID_NUMERIC_FIELD: VOUCHER_ERROR_CODES.VOUCHER_INVALID_NUMERIC_FIELD,
} as const;

export type VoucherRequestErrorCode =
  (typeof VOUCHER_REQUEST_ERROR_CODES)[keyof typeof VOUCHER_REQUEST_ERROR_CODES];
