/** Work OS domain error codes — projects, boards, phases, items */
export const WOS_ERROR_CODES = {
  // ── Entity not found ──
  PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',
  BOARD_NOT_FOUND: 'BOARD_NOT_FOUND',
  PHASE_NOT_FOUND: 'PHASE_NOT_FOUND',
  ITEM_NOT_FOUND: 'ITEM_NOT_FOUND',
  UPDATE_NOT_FOUND: 'UPDATE_NOT_FOUND',
  MEMBERSHIP_NOT_FOUND: 'MEMBERSHIP_NOT_FOUND',
  VIEW_NOT_FOUND: 'VIEW_NOT_FOUND',

  // ── Validation errors ──
  PROJECT_INVALID_DATA: 'PROJECT_INVALID_DATA',
  BOARD_INVALID_CONFIG: 'BOARD_INVALID_CONFIG',
  BOARD_LAST_DELETE_FORBIDDEN: 'BOARD_LAST_DELETE_FORBIDDEN',
  MEMBERSHIP_ALREADY_EXISTS: 'MEMBERSHIP_ALREADY_EXISTS',
  PHASE_SYSTEM_MANAGED_MODIFY_FORBIDDEN: 'PHASE_SYSTEM_MANAGED_MODIFY_FORBIDDEN',
  PHASE_DEFAULT_DELETE_FORBIDDEN: 'PHASE_DEFAULT_DELETE_FORBIDDEN',
  PHASE_SYSTEM_MANAGED_DELETE_FORBIDDEN: 'PHASE_SYSTEM_MANAGED_DELETE_FORBIDDEN',
  PHASE_REORDER_BASE_VERSION_INVALID: 'PHASE_REORDER_BASE_VERSION_INVALID',
  PHASE_REORDER_DUPLICATE_IDS: 'PHASE_REORDER_DUPLICATE_IDS',
  PHASE_REORDER_INVALID_PHASE_ID: 'PHASE_REORDER_INVALID_PHASE_ID',
  ITEM_PHASE_REQUIRED: 'ITEM_PHASE_REQUIRED',
  ITEM_CREATE_FAILED: 'ITEM_CREATE_FAILED',
  UNKNOWN_FIELD_KEY: 'UNKNOWN_FIELD_KEY',
  INVALID_FIELD_VALUE: 'INVALID_FIELD_VALUE',
  UNSUPPORTED_FIELD_DATA_TYPE: 'UNSUPPORTED_FIELD_DATA_TYPE',
  UNSUPPORTED_FIELD_SLOT: 'UNSUPPORTED_FIELD_SLOT',
  CHECKLIST_ITEM_NOT_FOUND: 'CHECKLIST_ITEM_NOT_FOUND',
  CHECKLIST_ORDER_IDS_INCOMPLETE: 'CHECKLIST_ORDER_IDS_INCOMPLETE',
  FIELD_SET_KEY_REQUIRED_FOR_SCOPED_RESOLUTION: 'FIELD_SET_KEY_REQUIRED_FOR_SCOPED_RESOLUTION',
  WOS_CONTRACT_CANONICAL_ID_MISSING: 'WOS_CONTRACT_CANONICAL_ID_MISSING',
  WOS_CONTRACT_INVALID_ARRAY_FIELD: 'WOS_CONTRACT_INVALID_ARRAY_FIELD',
  WOS_CONTRACT_INVALID_ID_ARRAY_ELEMENT: 'WOS_CONTRACT_INVALID_ID_ARRAY_ELEMENT',
  WOS_CONTRACT_INVALID_OBJECT_FIELD: 'WOS_CONTRACT_INVALID_OBJECT_FIELD',
  WOS_CONTRACT_INVALID_OBJECT_PAYLOAD: 'WOS_CONTRACT_INVALID_OBJECT_PAYLOAD',
  WOS_CONTRACT_INVALID_PAYLOAD: 'WOS_CONTRACT_INVALID_PAYLOAD',
  WOS_CONTRACT_INVALID_STRING_ARRAY_ELEMENT: 'WOS_CONTRACT_INVALID_STRING_ARRAY_ELEMENT',
  WOS_CONTRACT_MISSING_REQUIRED_FIELD: 'WOS_CONTRACT_MISSING_REQUIRED_FIELD',
  WOS_REQUEST_TENANT_REQUIRED: 'WOS_REQUEST_TENANT_REQUIRED',
  WOS_REQUEST_USER_REQUIRED: 'WOS_REQUEST_USER_REQUIRED',
  WOS_REQUEST_QUERY_POSITIVE_INTEGER_REQUIRED: 'WOS_REQUEST_QUERY_POSITIVE_INTEGER_REQUIRED',
  WOS_AUTH_SUBJECT_REQUIRED: 'WOS_AUTH_SUBJECT_REQUIRED',
  WOS_PROJECT_CONTEXT_ID_INVALID: 'WOS_PROJECT_CONTEXT_ID_INVALID',

  // ── State conflict ──
  PROJECT_ALREADY_ARCHIVED: 'PROJECT_ALREADY_ARCHIVED',
  PHASE_REORDER_CONFLICT: 'PHASE_REORDER_CONFLICT',
  VIEW_DEFAULT_DELETE_FORBIDDEN: 'VIEW_DEFAULT_DELETE_FORBIDDEN',
  VIEW_OWNER_DELETE_REQUIRED: 'VIEW_OWNER_DELETE_REQUIRED',
  VIEW_OWNER_EDIT_REQUIRED: 'VIEW_OWNER_EDIT_REQUIRED',

  // ── Authorization ──
  PROJECT_TENANT_MISMATCH: 'PROJECT_TENANT_MISMATCH',
  WOS_PROJECT_CONTEXT_UNRESOLVED: 'WOS_PROJECT_CONTEXT_UNRESOLVED',
  WOS_PROJECT_ROLE_INSUFFICIENT: 'WOS_PROJECT_ROLE_INSUFFICIENT',

  // ── Controller invariants ──
  WOS_BOARD_LIST_RETURNED_NON_ARRAY: 'WOS_BOARD_LIST_RETURNED_NON_ARRAY',
  WOS_BOARD_MEMBERSHIP_LIST_RETURNED_NON_ARRAY: 'WOS_BOARD_MEMBERSHIP_LIST_RETURNED_NON_ARRAY',
  WOS_BOARD_VIEW_LIST_RETURNED_NON_ARRAY: 'WOS_BOARD_VIEW_LIST_RETURNED_NON_ARRAY',
  WOS_PHASE_LIST_RETURNED_NON_ARRAY: 'WOS_PHASE_LIST_RETURNED_NON_ARRAY',
  WOS_PROJECT_ITEM_LIST_SUBITEMS_RETURNED_NON_ARRAY: 'WOS_PROJECT_ITEM_LIST_SUBITEMS_RETURNED_NON_ARRAY',
  WOS_UPDATE_LIST_RETURNED_NON_ARRAY: 'WOS_UPDATE_LIST_RETURNED_NON_ARRAY',

  // ── Generic fallbacks ──
  GENERIC_BAD_REQUEST: 'WOS_GENERIC_BAD_REQUEST',
  GENERIC_NOT_FOUND: 'WOS_GENERIC_NOT_FOUND',
  GENERIC_CONFLICT: 'WOS_GENERIC_CONFLICT',
  GENERIC_FORBIDDEN: 'WOS_GENERIC_FORBIDDEN',
  GENERIC_INTERNAL: 'WOS_GENERIC_INTERNAL',
} as const;

export type WosErrorCode = (typeof WOS_ERROR_CODES)[keyof typeof WOS_ERROR_CODES];
